# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=50)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrderHist',
            fields=[
                ('instore_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tel_no', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('remark', models.CharField(max_length=200)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InStoreOrderStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('order_status', models.CharField(max_length=50)),
                ('inStoreOrderHist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeStockControlApp.InStoreOrderHist')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('stock_type', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransHist',
            fields=[
                ('hist_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('in_out', models.CharField(max_length=50)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.CharField(max_length=50)),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeStockControlApp.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='instoreorderstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeStockControlApp.Stock'),
        ),
    ]
